export const prodEncomendaFAKE1 = {
  id: '1',
  remetente: 'Remetente 1',
  destinatario: 'Destinatario 1',
  logradouro: 'Rua tal 1',
  numero: '111',
  complemento: 'Complemento 1',
  cidade: 'Sao Paulo',
  estado: 'SP',
  quantidade: 1,
  preco_base: 15.0,
  acrescimo: 0,
  desconto: 0,
  preco_final: 0,
};

export const colecaoProdutosEncomendaFAKES = [
  {
    id: '1',
    remetente: 'Remetente 1',
    destinatario: 'Destinatario 1',
    logradouro: 'Rua tal 1',
    numero: '111',
    complemento: 'Complemento 1',
    cidade: 'Sao Paulo',
    estado: 'SP',
    quantidade: 1,
    preco_base: 15.0,
    acrescimo: 0,
    desconto: 0,
    preco_final: 0,
  },

  {
    id: '2',
    remetente: 'Remetente 2',
    destinatario: 'Destinatario 2',
    logradouro: 'Rua tal 2',
    numero: '222',
    complemento: 'Complemento 2',
    cidade: 'Sao Paulo',
    estado: 'SP',
    quantidade: 1,
    preco_base: 15.0,
    acrescimo: 0,
    desconto: 0,
    preco_final: 0,
  },

  {
    id: '3',
    remetente: 'Remetente 3',
    destinatario: 'Destinatario 3',
    logradouro: 'Rua tal 3',
    numero: '333',
    complemento: 'Complemento 3',
    cidade: 'Sao Paulo',
    estado: 'SP',
    quantidade: 1,
    preco_base: 15.0,
    acrescimo: 0,
    desconto: 0,
    preco_final: 0,
  },
];
