### 
# -------------------------------------
# CADASTRAR DADO
POST {{host}}/users
Content-Type: application/json

{
    "nome": "5",
    "email": "5",
    "password": "5"
}

### 
#------------------------------------