# import Perfil from '../perfil/perfil.gql'

type User {
  id: ID
  nome: String
  email: String
  password: String
  perfil: Perfil
}

input UserInput {
  nome: String
  email: String
  password: String
}

type Query {
  getUser(id: ID, email: String): User
  allUsers: [User]
  perfis: [Perfil]
}

type Mutation {
  createUser(data: UserInput): User!
  updateUser(id: ID, data: UserInput): User!
}
