# import Perfil from '../perfil/perfil.gql'

type User {
  id: ID
  nome: String
  email: String
  password: String
  perfil: Perfil
}

type Query {
  getUser(id: ID, email: String): User
  allUsers: [User]
  # perfis: [Perfil]
}

type Mutation {
  createUser(nome: String, email: String, password: String): User!
}
