type User {
  id: ID
  nome: String
  estabelecimento: String
  email: String
  password: String
}

input UserInput {
  nome: String
  estabelecimento: String
  email: String
  password: String
}

type Query {
  getUser(id: ID, email: String): User
  allUsers: [User]
}

type Mutation {
  createUser(data: UserInput): User!
}
