# import Cliente from '../../cliente/_entity/Cliente'

scalar Date

type Pedido {
  id: ID
  codigo: String
  quantidade: Int
  endereco: String
  createdAt: Date
  author: Cliente
}

input CreatePedidoInput {
  quantidade: Int!
  endereco: String!
  author: ID!
}

# ###########################################
# PONTOS DE ENTRADAS :: CONSULTAS & MUTACOES
# ##########################################

type Query {
  helloPedido: String
  getAllPedidos: [Pedido!]!
  getPedidoByCliente(idCliente: ID): [Pedido]
}

type Mutation {
  createPedido(input: CreatePedidoInput): Pedido
}
